# Site settings
author: Bruce Ruffin
title: Better Coding, Better Me, Better You
header-img: img/home-bg.png
email: bruffin1221@gmail.com
copyright_name: Bruce Ruffin
description: > # this means to ignore newlines until "baseurl:"
  Covers The Basic Of Coding and the Mindset of Learning It
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bruffin1221

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
